quarkus.http.body.uploads-directory=/data/photos
quarkus.http.body.delete-uploaded-files-on-end=true
quarkus.http.limits.max-body-size=50M

app.download-dir=/uploads/photos
app.photo-test-dir=/images
app.photos-system-dir=/data/photos